In [ ]:
import pandas as pd 
import numpy as np 
import csv
import matplotlib.pyplot as plt 
import seaborn as sns   #Python data visualization library based on matplotlib
from sklearn.linear_model import LinearRegression
from numpy.linalg import inv,lstsq
from numpy import dot, transpose
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split

In [ ]:
youtube_data = pd.read_csv('/content/youtube.csv')

In [ ]:
youdata = youtube_data.copy()

In [ ]:
youdata.head()

video_id trending_date  \
0  n1WpP7iowLc      17.14.11   
1  0dBIkQ4Mz1M      17.14.11   
2  5qpjK5DgCt4      17.14.11   
3  d380meD0W0M      17.14.11   
4  2Vv-BfVoq4g      17.14.11   

                                               title channel_title  \
0         Eminem - Walk On Water (Audio) ft. Beyoncé    EminemVEVO   
1                      PLUSH - Bad Unboxing Fan Mail     iDubbbzTV   
2  Racist Superman | Rudy Mancuso, King Bach & Le...  Rudy Mancuso   
3                           I Dare You: GOING BALD!?      nigahiga   
4        Ed Sheeran - Perfect (Official Music Video)    Ed Sheeran   

   category_id              publish_time  \
0           10  2017-11-10T17:00:03.000Z   
1           23  2017-11-13T17:00:00.000Z   
2           23  2017-11-12T19:05:24.000Z   
3           24  2017-11-12T18:01:41.000Z   
4           10  2017-11-09T11:04:14.000Z   

                                                tags     views    likes  \
0  Eminem|"Walk"|"On"|"Water"|"Aftermath/Shady/In...  17158579   787425   
1  plush|"bad unboxing"|"unboxing"|"fan mail"|"id...   1014651   127794   
2  racist superman|"rudy"|"mancuso"|"king"|"bach"...   3191434   146035   
3  ryan|"higa"|"higatv"|"nigahiga"|"i dare you"|"...   2095828   132239   
4  edsheeran|"ed sheeran"|"acoustic"|"live"|"cove...  33523622  1634130   

   dislikes  comment_count                                  thumbnail_link  \
0     43420         125882  https://i.ytimg.com/vi/n1WpP7iowLc/default.jpg   
1      1688          13030  https://i.ytimg.com/vi/0dBIkQ4Mz1M/default.jpg   
2      5339           8181  https://i.ytimg.com/vi/5qpjK5DgCt4/default.jpg   
3      1989          17518  https://i.ytimg.com/vi/d380meD0W0M/default.jpg   
4     21082          85067  https://i.ytimg.com/vi/2Vv-BfVoq4g/default.jpg   

   comments_disabled  ratings_disabled  video_error_or_removed  \
0              False             False                   False   
1              False             False                   False   
2              False             False                   False   
3              False             False                   False   
4              False             False                   False   

                                         description  
0  Eminem's new track Walk on Water ft. Beyoncé i...  
1  STill got a lot of packages. Probably will las...  
2  WATCH MY PREVIOUS VIDEO ▶ \n\nSUBSCRIBE ► http...  
3  I know it's been a while since we did this sho...  
4  🎧: https://ad.gt/yt-perfect\n💰: https://atlant...

Identifying unique values in the dataset, here i am finding out all the unique values in the category to know what all categories present in the dataset

In [ ]:
youdata.category_id.unique()

array([10, 23, 24, 25, 22, 26,  1, 28, 20, 17, 29, 15, 19,  2, 27, 43])

Finding Missing values in the dataset, it displays true if the dataset has missing values

In [ ]:
youdata.isnull()

video_id  trending_date  title  channel_title  category_id  \
0        False          False  False          False        False   
1        False          False  False          False        False   
2        False          False  False          False        False   
3        False          False  False          False        False   
4        False          False  False          False        False   
...        ...            ...    ...            ...          ...   
4153     False          False  False          False        False   
4154     False          False  False          False        False   
4155     False          False  False          False        False   
4156     False          False  False          False        False   
4157     False          False  False          False        False   

      publish_time   tags  views  likes  dislikes  comment_count  \
0            False  False  False  False     False          False   
1            False  False  False  False     False          False   
2            False  False  False  False     False          False   
3            False  False  False  False     False          False   
4            False  False  False  False     False          False   
...            ...    ...    ...    ...       ...            ...   
4153         False  False  False  False     False          False   
4154         False  False  False  False     False          False   
4155         False  False  False  False     False          False   
4156         False  False  False  False     False          False   
4157         False  False  False  False     False          False   

      thumbnail_link  comments_disabled  ratings_disabled  \
0              False              False             False   
1              False              False             False   
2              False              False             False   
3              False              False             False   
4              False              False             False   
...              ...                ...               ...   
4153           False              False             False   
4154           False              False             False   
4155           False              False             False   
4156           False              False             False   
4157           False              False             False   

      video_error_or_removed  description  
0                      False        False  
1                      False        False  
2                      False        False  
3                      False        False  
4                      False        False  
...                      ...          ...  
4153                   False        False  
4154                   False        False  
4155                   False        False  
4156                   False         True  
4157                   False        False  

[4158 rows x 16 columns]

Replacing missing values and null values with number '0'

In [ ]:
youdata=youdata.fillna(0)

In [ ]:
youdata1=youdata[["category_id","views","likes","dislikes","comment_count"]]

In [ ]:
youdata1.head()

category_id     views    likes  dislikes  comment_count
0           10  17158579   787425     43420         125882
1           23   1014651   127794      1688          13030
2           23   3191434   146035      5339           8181
3           24   2095828   132239      1989          17518
4           10  33523622  1634130     21082          85067

In [ ]:
X=youdata1.iloc[:,0].values
Y=youdata1.iloc[:,1:].values

Spliting dataset into test (20%) and train(80%)

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=0.20)

Normalizing the data using standard scaler, since the numbers in the dataset are huge and in different units, we are normalizing dataset using standard scaler method which scales using mean and standard deviation.

In [ ]:
scaler = StandardScaler()
scaler.fit(y_train)

y_train = scaler.transform(y_train)
y_test = scaler.transform(y_test)



KNN model fitting considering K=5 and metric = euclidean

In [ ]:
from sklearn.neighbors import KNeighborsClassifier
classifier = KNeighborsClassifier(n_neighbors=5,metric='euclidean')
classifier.fit(y_train, X_train)
X_pred = classifier.predict(y_test)

Confusion matrix, accuracy measures, classification report

In [ ]:
from sklearn.metrics import classification_report, confusion_matrix
print(confusion_matrix(X_test, X_pred))
print(classification_report(X_test, X_pred))

[[ 14   0   1   1   2   0   2   4   5   8   1   1   0   0   0]
 [  0   0   0   0   1   0   0   2   0   5   0   0   0   0   0]
 [  6   0  30   0   2   1   2   4   7  10   2   2   1   1   1]
 [  1   0   0   1   0   0   1   0   1   2   1   0   1   0   0]
 [  5   3   7   0  22   0   2   4   6  15   5   0   0   0   0]
 [  0   0   0   0   0   1   0   0   0   4   0   0   0   0   0]
 [  1   1   2   0   2   0   3   1   0   4   0   2   0   0   0]
 [  6   0   6   0   4   0   3  22   8  26  10   1   1   2   0]
 [  3   2  10   2   1   0   3   5  38  22   5   2   2   1   0]
 [ 13   1  20   2  16   3   5  27  16 131  18   3   1   4   2]
 [  2   0   1   2   6   0   1   6   4  23  29   0   0   2   0]
 [  2   0   5   1   0   0   5   4   5   9   0   6   1   0   0]
 [  0   1   0   0   2   2   1   1   1  10   2   1   2   1   0]
 [  3   1   2   0   1   1   2   2   2   7   0   0   2   6   0]
 [  0   0   0   0   0   0   0   0   0   2   0   0   0   0   2]]
              precision    recall  f1-score   support


KNN model fitting considering K=3 and metric = manhattan

In [ ]:
from sklearn.neighbors import KNeighborsClassifier
classifier = KNeighborsClassifier(n_neighbors=3,metric='manhattan')
classifier.fit(y_train, X_train)
X_pred = classifier.predict(y_test)


Confusion matrix, accuracy measures, classification report

In [ ]:
from sklearn.metrics import classification_report, confusion_matrix
print(confusion_matrix(X_test, X_pred))
print(classification_report(X_test, X_pred))

[[ 19   1   2   1   5   0   1   1   3   6   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0   1   7   0   0   0   0   0   0]
 [  8   0  37   0   1   1   2   2   3   9   1   1   2   1   1   0]
 [  3   0   0   1   0   0   1   0   1   2   0   0   0   0   0   0]
 [  9   3  12   0  21   0   2   5   3  11   3   0   0   0   0   0]
 [  0   0   0   0   0   1   0   0   0   4   0   0   0   0   0   0]
 [  2   2   1   0   1   0   5   3   0   1   0   1   0   0   0   0]
 [  5   1   8   0   7   1   5  23   3  23   6   1   2   4   0   0]
 [  2   5  10   3   6   1   1   5  35  22   2   3   1   0   0   0]
 [ 24   2  20   3  19   3   7  27  16 110  23   4   0   2   0   2]
 [  5   1   3   3   4   0   1   6   4  18  28   0   0   2   1   0]
 [  6   0   3   1   1   1   4   3   4   6   1   7   1   0   0   0]
 [  0   0   2   0   4   2   0   3   1   8   2   0   1   1   0   0]
 [  5   2   5   0   1   2   0   3   3   3   0   0   0   5   0   0]
 [  0   0   0   0   0   0   0   0   0   0   0   0   0   0   0 

/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


KNN model fitting considering K=4 and metric = minkowski

In [ ]:
from sklearn.neighbors import KNeighborsClassifier
classifier = KNeighborsClassifier(n_neighbors=4,metric='minkowski')
classifier.fit(y_train, X_train)
X_pred = classifier.predict(y_test)


Confusion matrix, accuracy measures, classification report

In [ ]:
from sklearn.metrics import classification_report, confusion_matrix
print(confusion_matrix(X_test, X_pred))
print(classification_report(X_test, X_pred))

[[ 18   0   0   1   2   0   4   0   3   8   2   1   0   0   0   0]
 [  0   0   0   0   1   0   0   1   0   6   0   0   0   0   0   0]
 [  6   0  29   0   2   1   1   2   6  15   1   1   2   1   1   1]
 [  1   0   0   1   0   0   1   0   1   2   1   0   1   0   0   0]
 [  7   3   8   0  21   0   2   3   6  15   4   0   0   0   0   0]
 [  0   0   0   1   0   1   0   0   0   3   0   0   0   0   0   0]
 [  1   1   2   0   2   0   2   3   0   4   0   1   0   0   0   0]
 [  4   1   4   0   6   1   3  21   5  29  11   1   1   2   0   0]
 [  6   4  10   3   4   0   3   5  33  21   3   2   2   0   0   0]
 [ 18   3  18   1  17   4   3  26  18 117  21   8   1   4   0   3]
 [  5   0   3   3   6   0   1   3   6  21  25   0   0   2   1   0]
 [  4   0   6   1   0   0   4   2   4   6   1   8   2   0   0   0]
 [  0   1   1   0   3   2   1   0   1  10   2   0   2   1   0   0]
 [  5   1   6   0   1   2   1   2   1   3   0   0   1   6   0   0]
 [  0   0   0   0   0   0   0   0   0   0   0   0   0   0   0 

/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


From the above reports we can say that KNN algorithm is not optimum for this dataset as the result for the test data is not precisely classified into any of the classification.

Naïve Bayes Classification of the same dataset

In [ ]:
from sklearn.naive_bayes import GaussianNB
gnb = GaussianNB()
gnb.fit(y_train, X_train)

X_pred = gnb.predict(y_test)

# comparing actual response values (y_test) with predicted response values (y_pred)
from sklearn import metrics
print("Gaussian Naive Bayes model accuracy(in %):", metrics.accuracy_score(X_test, X_pred)*100)

Gaussian Naive Bayes model accuracy(in %): 7.572115384615384


As the accuracy of prediction is very low, we can interpret that Gussian naive bayes is not optimum for my dataset